# Generated by Django 4.1.3 on 2022-12-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='file',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
