# Generated by Django 4.1.3 on 2022-12-31 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0002_alter_map_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamecore.mapcreator'),
        ),
    ]
