# Generated by Django 4.1.3 on 2023-01-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0007_remove_map_class_room_map_class_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='class_room',
        ),
        migrations.AddField(
            model_name='player',
            name='class_room',
            field=models.ManyToManyField(blank=True, to='gamecore.classroom'),
        ),
    ]
