# Generated by Django 4.1.3 on 2023-01-03 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0008_remove_player_class_room_player_class_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='classroom')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_room_code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamecore.classroomcategory'),
        ),
    ]
