# Generated by Django 4.1.3 on 2023-01-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0009_classroomcategory_classroom_class_room_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_room_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
