# Generated by Django 4.1.3 on 2023-01-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecore', '0010_alter_classroom_class_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
